# -*- coding: utf-8 -*-
"""regex

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vO2qhgoU4ac27bjsjlynDEYxy3dtWV-K
"""

# A Regular Expression (RegEx) is a sequence of characters that defines a search pattern. For example,

# ^a...s$
# The above code defines a RegEx pattern. The pattern is: any five letter string starting with a and ending with s.

# MetaCharacters
# Metacharacters are characters that are interpreted in a special way by a RegEx engine. Here's a list of metacharacters:

# [] . ^ $ * + ? {} () \ |


# following programs show the usage of some basic regex functions in python 



import re
# a program to match 5 letter dtring starting with a and ending with s
pattern = '^a...s$'
test_string = 'abyss'
result = re.match(pattern, test_string)

if result:
  print("Search successful.")
else:
  print("Search unsuccessful.")

# a program use use re.findall() that finds all numbers in a string 


string = 'hello 12 hi 89. Howdy 34'
pattern = '\d+'

result = re.findall(pattern, string) 
print(result)

# A program to use re.split()
# The re.split method splits the string where there is a match and returns a list of strings where the splits have occurred.



string = 'Twelve:12 Eighty nine:89.'
pattern = '\d+'

result = re.split(pattern, string) 
print(result)

# Program to use re.sub() and remove all whitespaces
import re

# multiline string
string = 'abc 12\
de 23 \n f45 6'

# matches all whitespace characters
pattern = '\s+'

# empty string
replace = ''

new_string = re.sub(pattern, replace, string) 
print(new_string)

# a program to use re.search()
string = "Python is fun"

# check if 'Python' is at the beginning
match = re.search('\APython', string)

if match:
  print("pattern found inside the string")
else:
  print("pattern not found")

